# site settings
title: FTSF
subtitle: The Fair Transition Standards Forum
email: agrayso6@jhu.edu
description: Toward fair and inclusive decarbonization.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fairtransitionstandardsforum.github.io/" # the base hostname & protocol for your site
author:
street_address:
city: Baltimore
state: MD
zip_code: 21211
country: United States of America
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub:
  GitLab:
  Instagram:
  LinkedIn:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 




